language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-vm-boilerplate' ]; then cd .. && eval "mv $currentfolder generator-vm-boilerplate" && cd generator-vm-boilerplate; fi

