language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-vm' ]; then cd .. && eval "mv $currentfolder generator-vm" && cd generator-vm; fi

